Model
double Model::a
Referenced by linearModel, Model, nonlinearModel.
double Model::b
Referenced by linearModel, Model, nonlinearModel.
double Model::c
Referenced by Model, nonlinearModel.
double Model::d
Referenced by Model, nonlinearModel.
double Model::y_prev1
Referenced by getCurrentValue, init, linearModel, Model, nonlinearModel, setCurrentValue.
double Model::y_prev2
Referenced by init, linearModel, Model, nonlinearModel.
double Model::u_prev1
Referenced by init, linearModel, Model, nonlinearModel.
double Model::u_prev2
Referenced by init, linearModel, Model, nonlinearModel.
Model::Model(double a_val=0.2, double b_val=0.3, double c_val=0.4, double d_val=0.5)
Конструктор модели
a_val Коэффициент a (по умолчанию 0.2) b_val Коэффициент b (по умолчанию 0.3) c_val Коэффициент c (по умолчанию 0.4) d_val Коэффициент d (по умолчанию 0.5)
References a, b, c, d, u_prev1, u_prev2, y_prev1, y_prev2.
void Model::init(double y0, double y1, double u0, double u1)
Инициализация начальных условий
y0 Начальное значение y[k-2] y1 Начальное значение y[k-1] u0 Начальное значение u[k-2] u1 Начальное значение u[k-1]
References u_prev1, u_prev2, y_prev1, y_prev2.
Referenced by main.
double Model::linearModel(double u)
Линейная модель объекта
u Текущее управляющее воздействие Текущее значение выхода
References a, b, u_prev1, u_prev2, y_prev1, y_prev2.
Referenced by main.
double Model::nonlinearModel(double u)
Нелинейная модель объекта
u Текущее управляющее воздействие Текущее значение выхода Включает ограничение выходных значений ±1000
References a, b, c, d, u_prev1, u_prev2, y_prev1, y_prev2.
Referenced by main.
double Model::getCurrentValue() const
Получение текущего значения выхода
Текущее значение y[k-1]
References y_prev1.
Referenced by main.
void Model::setCurrentValue(double value)
Установка текущего значения выхода
value Новое значение
References y_prev1.