pid.cpp
void initPID(PID &pid, double q0, double q1, double q2)
References PID::e_prev1, PID::e_prev2, PID::q0, PID::q1, PID::q2, PID::u_prev.
Referenced by main, TEST, TEST.
double updatePID(PID &pid, double e)
References PID::e_prev1, PID::e_prev2, PID::q0, PID::q1, PID::q2, PID::u_prev.
Referenced by main, TEST, TEST.