add_test([=[LinearModelTest.BaseCase]=]  C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src/Debug/runTests_ii02803.exe [==[--gtest_filter=LinearModelTest.BaseCase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LinearModelTest.BaseCase]=]  PROPERTIES WORKING_DIRECTORY C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LinearModelTest.WithNonZeroY]=]  C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src/Debug/runTests_ii02803.exe [==[--gtest_filter=LinearModelTest.WithNonZeroY]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LinearModelTest.WithNonZeroY]=]  PROPERTIES WORKING_DIRECTORY C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NonlinearModelTest.BaseCase]=]  C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src/Debug/runTests_ii02803.exe [==[--gtest_filter=NonlinearModelTest.BaseCase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NonlinearModelTest.BaseCase]=]  PROPERTIES WORKING_DIRECTORY C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NonlinearModelTest.WithValues]=]  C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src/Debug/runTests_ii02803.exe [==[--gtest_filter=NonlinearModelTest.WithValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NonlinearModelTest.WithValues]=]  PROPERTIES WORKING_DIRECTORY C:/Users/vimor/OTIS-2025/trunk/ii02803/task_02/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  runTests_ii02803_TESTS LinearModelTest.BaseCase LinearModelTest.WithNonZeroY NonlinearModelTest.BaseCase NonlinearModelTest.WithValues)
