add_test([=[ModelTest.LinearZeroParams]=]  C:/Users/MSI/Documents/OTIS-2025/build_test/Debug/task_03_ii02807_test.exe [==[--gtest_filter=ModelTest.LinearZeroParams]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelTest.LinearZeroParams]=]  PROPERTIES WORKING_DIRECTORY C:/Users/MSI/Documents/OTIS-2025/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelTest.LinearBasic]=]  C:/Users/MSI/Documents/OTIS-2025/build_test/Debug/task_03_ii02807_test.exe [==[--gtest_filter=ModelTest.LinearBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelTest.LinearBasic]=]  PROPERTIES WORKING_DIRECTORY C:/Users/MSI/Documents/OTIS-2025/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelTest.NonlinearWithoutControlTerms]=]  C:/Users/MSI/Documents/OTIS-2025/build_test/Debug/task_03_ii02807_test.exe [==[--gtest_filter=ModelTest.NonlinearWithoutControlTerms]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelTest.NonlinearWithoutControlTerms]=]  PROPERTIES WORKING_DIRECTORY C:/Users/MSI/Documents/OTIS-2025/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModelTest.NonlinearWithSin]=]  C:/Users/MSI/Documents/OTIS-2025/build_test/Debug/task_03_ii02807_test.exe [==[--gtest_filter=ModelTest.NonlinearWithSin]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModelTest.NonlinearWithSin]=]  PROPERTIES WORKING_DIRECTORY C:/Users/MSI/Documents/OTIS-2025/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PIDTest.ZeroError]=]  C:/Users/MSI/Documents/OTIS-2025/build_test/Debug/task_03_ii02807_test.exe [==[--gtest_filter=PIDTest.ZeroError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PIDTest.ZeroError]=]  PROPERTIES WORKING_DIRECTORY C:/Users/MSI/Documents/OTIS-2025/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PIDTest.ConstantError]=]  C:/Users/MSI/Documents/OTIS-2025/build_test/Debug/task_03_ii02807_test.exe [==[--gtest_filter=PIDTest.ConstantError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PIDTest.ConstantError]=]  PROPERTIES WORKING_DIRECTORY C:/Users/MSI/Documents/OTIS-2025/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  task_03_ii02807_test_TESTS ModelTest.LinearZeroParams ModelTest.LinearBasic ModelTest.NonlinearWithoutControlTerms ModelTest.NonlinearWithSin PIDTest.ZeroError PIDTest.ConstantError)
